### ISSUE TITLE
Make it work on HHVM

### ISSUE THREAD

**Issue by weierophinney** [zfcampus/zf-configuration#12]
We currently fail on HHVM:

- https://travis-ci.org/zfcampus/zf-configuration/jobs/70921088

Primarily, the issue is in deleting keys, which should help isolate where the problem is on that platform.

**Comment by ezimuel** [comment]
@weierophinney I just tried to reproduce the issue on 34vl.org using HHVM 3.6 and 3.7 and it seems to work fine: http://3v4l.org/6oAYb. I noticed that Travis CI uses HHVM 3.5, maybe this is the issue.

**Comment by weierophinney** [comment]
Closing based on feedback from @ezimuel ; hopefully Travis-CI will update its HHVM support soon. :)
