### ISSUE TITLE
PatchKey uses ReplaceKey

### ISSUE THREAD

**Issue by TomHAnderson** [zfcampus/zf-configuration#21]
The function `patchKey` does not actually patch a key.  It uses `replaceKey` to do the heavy lifting:
https://github.com/zfcampus/zf-configuration/blob/master/src/ConfigResource.php#L118

I submit patchKey should read the current key and merge the arrays.

**Comment by TomHAnderson** [comment]
This is still a big issue for zf-apigility-doctrine users because the query_create_filters and query_providers are all lost.  These are a major source of security information for an app.

This issue was closed for 1.3.1 which was reverted to 1.3.2 and remains unfixed today.  Will you please re-open this issue and prioritize it high.

**Comment by TomHAnderson** [comment]
Seeing this fixed is a priority to me so I'll dig through it to see about fixing the library and fixing the admin.  I (should) have down time in a couple weeks in SF to investigate.

**Comment by weierophinney** [comment]
This repository has been closed and moved to laminas-api-tools/api-tools-configuration; a new issue has been opened at https://github.com/laminas-api-tools/api-tools-configuration/issues/2.
