### ISSUE TITLE
Apigility admin config save have error after zf-configuration last changes

### ISSUE THREAD

**Issue by developer-devPHP** [zfcampus/zf-configuration#28]
After #25 changes apigility configuration save have errors. Here is error message
``  E_WARNING : Illegal offset type ``
`` zfcampus/zf-configuration/src/ConfigResource.php at line : 113 ``

Error trace

- 0  handler() called at [/var/www/vendor/zfcampus/zf-configuration/src/ConfigResource.php:113]
- 1  ZF\Configuration\ConfigResource->patchKey() called at [/var/www/vendor/zfcampus/zf-apigility-admin/src/Model/InputFilterModel.php:153]
- 2  ZF\Apigility\Admin\Model\InputFilterModel->addInputFilter() called at [/var/www/vendor/zfcampus/zf-apigility-admin/src/Model/InputFilterModel.php:53]
- 3  ZF\Apigility\Admin\Model\InputFilterModel->update() called at [/var/www/vendor/zfcampus/zf-apigility-admin/src/Controller/InputFilterController.php:92]
- 4  ZF\Apigility\Admin\Controller\InputFilterController->indexAction() called at [/var/www/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php:78]
- 5  Zend\Mvc\Controller\AbstractActionController->onDispatch() called at [/var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php:322]
- 6  Zend\EventManager\EventManager->triggerListeners() called at [/var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php:179]
- 7  Zend\EventManager\EventManager->triggerEventUntil() called at [/var/www/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php:106]
- 8  Zend\Mvc\Controller\AbstractController->dispatch() called at [/var/www/vendor/zendframework/zend-mvc/src/DispatchListener.php:138]
- 9  Zend\Mvc\DispatchListener->onDispatch() called at [/var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php:322]
- 10 Zend\EventManager\EventManager->triggerListeners() called at [/var/www/vendor/zendframework/zend-eventmanager/src/EventManager.php:179]
- 11 Zend\EventManager\EventManager->triggerEventUntil() called at [/var/www/vendor/zendframework/zend-mvc/src/Application.php:332]
- 12 Zend\Mvc\Application->run() called at [/var/www/public/index.php:150]

**Comment by developer-devPHP** [comment]
problem her 
`` [$key => $value] ``

because $key and $value both are array

here is simple test and you can get similar error

```php

$key = [
'testkey1',
'testkey2',
'testkey3'
];

$value = [
'testvalue1',
'testvalue2',
'testvalue3'
];

var_dump([$key => $value]);


```

**Comment by samsonasik** [comment]
I got same error after composer update to v1.3.1
